//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SettleIn {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class PlayerSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static PlayerSettings defaultInstance = ((PlayerSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PlayerSettings())));
        
        public static PlayerSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SettleInCommon.User.XmlUserCredentials Credentials {
            get {
                return ((global::SettleInCommon.User.XmlUserCredentials)(this["Credentials"]));
            }
            set {
                this["Credentials"] = value;
            }
        }
    }
}
